In [ ]:
import cv2
import numpy as np
img = cv2.imread("./images/image1.jpeg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 75, 150)
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 30, maxLineGap=50,minLineLength=500)
print (lines)
for line in lines:
   x1, y1, x2, y2 = line[0]
   cv2.line(img, (x1, y1), (x2, y2), (50, 0, 128), 1)
cv2.imshow("linesEdges", edges)
cv2.imshow("linesDetected", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[  0 123 539 278]]

 [[  2  56 539 170]]

 [[  1   3 539  98]]

 [[  0 306 539 306]]

 [[ 24  12 539 102]]

 [[  7   6 539 100]]

 [[ 35 304 539 251]]

 [[  4   7 539 101]]

 [[  1  56 523 167]]

 [[ 14 129 539 280]]

 [[ 10  53 539 165]]

 [[ 31  84 539 182]]]
